---
title: "wind_speed"
author: "Jake Eisaguirre"
date: "2/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(raster)
library(REdaS)
library(sf)
library(lubridate)
library(terra)
library(jsonlite)
library(httr)
library(ggquiver)
library(gstat)
library(automap)
library(stars)
library(magick)
library(metR)

```


# download u and v component of wind
```{r}

url_ucomp <- ("http://api.planetos.com/v1/datasets/noaa_nam_awips_12/area?polygon=[[-121.40,34.75],[-117.06,34.75],[-117.06,32.36],[-121.40,32.36],[-121.40,34.75]]&apikey=e5102ee5d77e422eaa5dea4124ba2165&csv=true&count=500000&variables=u-component_of_wind_planetary_boundary")

wind_u <- download.file(url_ucomp, here("data", "wind_u.csv"))

wind_u <- here("data", "wind_u.csv") %>% 
  read_csv()




url_vcomp <- "http://api.planetos.com/v1/datasets/noaa_nam_awips_12/area?polygon=[[-121.40,34.75],[-117.06,34.75],[-117.06,32.36],[-121.40,32.36],[-121.40,34.75]]&apikey=e5102ee5d77e422eaa5dea4124ba2165&csv=true&count=500000&variables=v-component_of_wind_planetary_boundary"

download.file(url_vcomp, here("data", "wind_v.csv"))

wind_v <- here("data", "wind_v.csv") %>% 
  read_csv()

```

# convert u and v
```{r}

wind_data <- left_join(wind_u, wind_v, by = c("axis:latitude", "axis:longitude"))

wind_data <- wind_data %>% 
  as.data.frame() %>% 
  dplyr::select(!c("axis:time.y", "axis:reftime.y")) 

names(wind_data) <- substring(names(wind_data), 6)

wind_data <- wind_data %>% 
  rename(reftime = reftime.x) %>% 
  rename(date = time.x) %>% 
  rename(u = `u-component_of_wind_planetary_boundary`) %>% 
  rename(v = `v-component_of_wind_planetary_boundary`)

wind_angle <- wind_data %>% 
  dplyr::select(c("latitude", "longitude", "u", "v", "date"))

wind_ras <- wind_data %>%
  mutate(wind = ((sqrt((u^2) + (v^2)))*1.94), 
         angle = rad2deg(atan2(u, v)),
         angle = ifelse(angle < 190, abs(angle)+180),
         date = parse_date_time(date, "Ymd HMS", tz = "America/Los_Angeles" ),
         date = as.factor(date)) %>%
  dplyr::select(-c(u, v)) %>% 
  group_by(date) %>% 
  dplyr::select(!c("reftime", "angle")) %>% 
  rename(x = longitude) %>% 
  rename(y = latitude)%>% 
  dplyr::select(x, everything()) %>% 
  relocate(wind, .before = date) %>% 
  ungroup()


```


# Shape Files
```{r}
islands <- read_sf(here('data', "shape",'island_shape', "channel_islands.shp")) %>% 
  mutate(geometry = st_transform(geometry, crs = 4326))

ca <- read_sf(here('data', "shape","s_11au16", "s_11au16.shp")) %>% 
  mutate(geometry = st_transform(geometry, crs = 4326)) %>% 
  filter(NAME == "California") %>% 
  dplyr::select(geometry)

merged_shapes <- bind_rows(ca, islands)
```


# manual brick
```{r}
wind_1 <- wind_ras %>% 
  filter(date == unique(date)[[1]]) %>% 
  rasterFromXYZ() %>% 
  dropLayer(2)

wind_2 <- wind_ras %>% 
  filter(date == unique(date)[[2]]) %>% 
  rasterFromXYZ() %>% 
  dropLayer(2)

wind_3 <- wind_ras %>% 
  filter(date == unique(date)[[3]]) %>% 
  rasterFromXYZ() %>% 
  dropLayer(2)

wind_4 <- wind_ras %>% 
  filter(date == unique(date)[[4]]) %>% 
  rasterFromXYZ() %>% 
  dropLayer(2)

wind_5 <- wind_ras %>% 
  filter(date == unique(date)[[5]]) %>% 
  rasterFromXYZ() %>% 
  dropLayer(2)

wind_6 <- wind_ras %>% 
  filter(date == unique(date)[[6]]) %>% 
  rasterFromXYZ() %>% 
  dropLayer(2)

wind_7 <- wind_ras %>% 
  filter(date == unique(date)[[7]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_8 <- wind_ras %>% 
  filter(date == unique(date)[[8]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_9 <- wind_ras %>% 
  filter(date == unique(date)[[9]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_10 <- wind_ras %>% 
  filter(date == unique(date)[[10]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_11 <- wind_ras %>% 
  filter(date == unique(date)[[11]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_12 <- wind_ras %>% 
  filter(date == unique(date)[[12]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_13 <- wind_ras %>% 
  filter(date == unique(date)[[13]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_14 <- wind_ras %>% 
  filter(date == unique(date)[[14]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_15 <- wind_ras %>% 
  filter(date == unique(date)[[15]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_16 <- wind_ras %>% 
  filter(date == unique(date)[[16]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_17 <- wind_ras %>% 
  filter(date == unique(date)[[17]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_18 <- wind_ras %>% 
  filter(date == unique(date)[[18]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_19 <- wind_ras %>% 
  filter(date == unique(date)[[19]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_20 <- wind_ras %>% 
  filter(date == unique(date)[[20]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)


wind_21 <- wind_ras %>% 
  filter(date == unique(date)[[21]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_22 <- wind_ras %>% 
  filter(date == unique(date)[[22]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_23 <- wind_ras %>% 
  filter(date == unique(date)[[23]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_24 <- wind_ras %>% 
  filter(date == unique(date)[[24]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_25 <- wind_ras %>% 
  filter(date == unique(date)[[25]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_26 <- wind_ras %>% 
  filter(date == unique(date)[[26]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_27 <- wind_ras %>% 
  filter(date == unique(date)[[27]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_28 <- wind_ras %>% 
  filter(date == unique(date)[[28]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_29 <- wind_ras %>% 
  filter(date == unique(date)[[29]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_30 <- wind_ras %>% 
  filter(date == unique(date)[[30]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_31 <- wind_ras %>% 
  filter(date == unique(date)[[31]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_32 <- wind_ras %>% 
  filter(date == unique(date)[[32]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)


wind_33 <- wind_ras %>% 
  filter(date == unique(date)[[33]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_34 <- wind_ras %>% 
  filter(date == unique(date)[[34]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_35 <- wind_ras %>% 
  filter(date == unique(date)[[35]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_36 <- wind_ras %>% 
  filter(date == unique(date)[[36]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_37 <- wind_ras %>% 
  filter(date == unique(date)[[37]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_38 <- wind_ras %>% 
  filter(date == unique(date)[[38]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_39 <- wind_ras %>% 
  filter(date == unique(date)[[39]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_40 <- wind_ras %>% 
  filter(date == unique(date)[[40]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_41 <- wind_ras %>% 
  filter(date == unique(date)[[41]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_42 <- wind_ras %>% 
  filter(date == unique(date)[[42]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_43 <- wind_ras %>% 
  filter(date == unique(date)[[43]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_44 <- wind_ras %>% 
  filter(date == unique(date)[[44]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_45 <- wind_ras %>% 
  filter(date == unique(date)[[45]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_46 <- wind_ras %>% 
  filter(date == unique(date)[[46]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)

wind_47 <- wind_ras %>% 
  filter(date == unique(date)[[47]]) %>% 
  rasterFromXYZ()%>% 
  dropLayer(2)



ras_brick <- brick(wind_1, wind_2, wind_3, wind_4, wind_5, wind_6, wind_7,
                 wind_8,wind_9,wind_10,
               wind_11, wind_12, wind_13, wind_14, wind_15, wind_16, wind_17, wind_18,
               wind_19,wind_20,
               wind_21, wind_22, wind_23, wind_24, wind_25, wind_26, wind_27,
               wind_28,wind_29, wind_30, wind_31, wind_32, wind_33, wind_34, wind_35,
               wind_36, wind_37,
               wind_38, wind_39, wind_40, wind_41, wind_42, wind_43, wind_44, wind_45,
               wind_46, wind_47)



rm(wind_1, wind_2, wind_3, wind_4, wind_5, wind_6, wind_7,
                 wind_8,wind_9,wind_10,
               wind_11, wind_12, wind_13, wind_14, wind_15, wind_16, wind_17, wind_18,
               wind_19,wind_20,
               wind_21, wind_22, wind_23, wind_24, wind_25, wind_26, wind_27,
               wind_28,wind_29, wind_30, wind_31, wind_32, wind_33, wind_34, wind_35,
               wind_36, wind_37,
               wind_38, wind_39, wind_40, wind_41, wind_42, wind_43, wind_44, wind_45,
               wind_46, wind_47)
gc()

```

# ras re-sample
```{r}

# ras <- brick(xmn = -121.45,
#              xmx = -117.05,
#              ymn = 32.35,
#              ymx = 34.75)




# for(i in 1:levels(wind_ras$date)) {
#   
#   
#   test <- wind_ras %>%
#     filter(date == unique(date)[[i]])
#   
#   ras[[i]]<- rasterFromXYZ(test)
# 
# }




wind_res <- c(0.005, 0.005) 

new_ras_wind <- raster(xmn = -121.4,
                      xmx = -117.06,
                      ymn = 32.36,
                      ymx = 34.75,
                      res = wind_res)

re_samp_wind <- resample(ras_brick, new_ras_wind, method = "bilinear")

cropped_wind <- mask(re_samp_wind, merged_shapes, inverse = T)

final_ras_wind <- projectRaster(cropped_wind, crs = 4326)


```

# points
```{r}

wind_ras_data <- as.data.frame(rasterToPoints(final_ras_wind)) %>% 
  pivot_longer(!c(x,y), names_to = "date", values_to = "wind")

```

# pal
```{r}

wind_pal <- colorRampPalette(c("#606fb4", "#6070b4", "#3c6c9f", "#4788a6", "#488e9b", "#4d8d7b", "#4da048", "#55a042", "#749c38", "#9f7b49", "#9c655b", "#8d455b", "#8e436f", "#95498c", "#6d5d9a"))

wind_limits <- c(0,60)



```


```{r}
wind.list = lapply(sort(unique(wind_ras_data$date)), function(i) {
  ggplot(data = wind_ras_data[wind_ras_data$date==i,], aes(y=y, x=x)) +
  geom_raster(aes(fill = wind), interpolate = T) +
  facet_wrap(~as.factor(date)) +
  scale_fill_gradientn(colours = wind_pal(100), limits = wind_limits) +
  theme_classic() +
  theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),legend.position="none",
          panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(),
        plot.margin=unit(c(0,0,0,0), "null"),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  coord_sf(xlim = c(-121.45, -117.06), ylim = c(32.36, 34.75), expand = F)
})


```

```{r}
new.wind.list <- list()

for(i in seq_along(wind.list)){
  
  new.wind.list[[i]] <- wind.list[[i]] +
    geom_spoke(data = wind.arrows, aes(y=y, x=x, angle = angle, 
                                     radius = scales::rescale(wind, c(.02, .15))), 
             arrow=arrow(length = unit(0.2,"cm")))

}

swell.list[[1]]

wind.arrows <- wind_angle %>% 
    filter(longitude %in% sort(unique(longitude))[c(T, F, F, F, F, F, F, F, 
                                    F, F, F, F, F, F, F, F, F)], 
           latitude %in% sort(unique(latitude))[c(T, F, F, F, F, F, F, F, 
                                    F, F, F, F, F, F, F, F, F)])

test_wind <- wind.arrows %>% 
  filter(date == "2022-04-29 12:00:00") %>% 
  dplyr::select(!c("date"))

a <- swell.list[[1]] 

a +
  geom_arrow(data = test_wind, aes(x=u, y=v))

```


```{r}
w_dpi <- c(215)

unlink("pngs/old/*")

for(i in 1:length(new.swell.list)){
  
  ggsave(paste0(here('pngs', 'old'), "/", wind_ras_data$date[i], '.png'), dpi = w_dpi, 
         bg = "transparent", plot = new.swell.list[[i]])
}
```

```{r}
unlink("pngs/site_ready/*")

for(i in 1:length(swell.list)){
  hs <- image_read(paste0(here('pngs', 'old'), "/", wind_ras_data$date[i], '.png'))
  hs <- image_trim(hs)
  hs <- image_transparent(hs, "white")
  image_write(hs, paste0(here('pngs', 'site_ready'), "/", wind_ras_data$date[i], '.png'))
}

```


```{r}

wind_ras <- wind_ras %>% 
  filter(date == "2022-04-26 12:00:00")

wind_data <- wind_data %>% 
  filter(date == "2022-04-12 12:00:00")

wind_ras_t <- wind_ras %>% 
    filter(longitude %in% sort(unique(longitude))[c(T, F, F, F, F, F, F, F, 
                                    F, F, F, F, F, F, F, F, F)], 
           latitude %in% sort(unique(latitude))[c(T, F, F, F, F, F, F, F, 
                                    F, F, F, F, F, F, F, F, F)])

ggplot() +
  geom_raster(a, interpolate = T) 

+
  geom_spoke(data = wind_ras_t, aes(y=latitude, x=longitude, angle = angle, 
                                           radius = scales::rescale(wind, c(.02, .15))), 
               arrow=arrow(length = unit(0.2,"cm"))) +
  theme_classic() +
  scale_fill_viridis_c(option = "turbo")
  
  +
  geom_sf(data = cha, color = "black", fill = "grey60")
```

